### ISSUE TITLE
ppconsul windows dll libs

### ISSUE THREAD

**Issue by AmramXing** [oliora/ppconsul#20]
I want to build ppconsul in windows by myself. I found it is very difficult to do it, because needd boots and curl install and so on.
Can you give me a comiled ppconsul libray(dll, lib) form windows to me, I can use ppconsul library in my windows project.

**Comment by oliora** [comment]
Hi, you only need curl library compiled and you can easily download one along with headers from the curl official web-site. For boost you only need headers which means that you can just download a zip archive with sources from the boost official site and unpack it.

**Comment by AmramXing** [comment]
I just want dll or lib file to use, I don't want to compile code.

**Comment by oliora** [comment]
Sorry, I can not provide it to you. If I do this there will be someone else next week asking me for a Linux binary version of library or you will ask me for an update or whatewer else. But I don’t have time to satisfy all such requests. And it would be unfair if I satisfy your request but deny other’s. So you have to build it by yourself. That’s not hard, just follow the docs and my previous comment.

**Comment by AmramXing** [comment]
@oliora In windows C++ program, there ar two kind library: dynamic library(.dll) and static library(.lib)

The programer only need to link dll or lib in their project, It is so convenient.

**Comment by oliora** [comment]
Sure. But you link a library with your compiled code. You need to compile *your* code anyway. To compile your code that uses ppconsul you need to include boost headers so you need to have boost headers on your machine anyway.

Ppconsul depends on libcurl.dll so to run your app that’t linked with ppconsul library you need to have libcurl.dll on your machine anyway.

That’s what I mean by saying that you need to have this dependencies on your machine regardless of whether you have ppconsul library precompiled or not.

I assume that you might not care about compiling the application code or running the application but only about getting ppconsul library binary. This could happen if you don’t understand the whole picture yet or because someone has assigned such a sub-task to you and you’re trying me to do your job ;) In any case you have to go thru ppconsul compilation.

So to help you, you need the following:
1.  download and install Visual Studio 2013 update 3 or newer (Command Line C++ Tools version would be enough)
2. download and install CMake 3.1 or newer
3. download and unzip sources of boost 1.55 or newer
4. download and install/unzip libcurl (with  headers)
5. follow ppconsul readme to compile it

**Comment by AmramXing** [comment]
Ok, I know.
